In [6]:
# Read the file into dataframes
import pandas as pd
df = pd.read_excel("DATA BI.xlsx",index_col=False,keep_default_na=True,sheet_name='DEPENSES', header=2)

In [7]:
df.columns

Index(['N°', 'Unnamed: 1', 'DATE', 'NCG', 'ICG', 'NCT', 'NCG.1', 'N° FCT',
       'DESCRIPTION', 'SODEXO', 'HT', 'TVA', 'TF', 'TTC', 'RS', 'NET RS',
       'PAIEMENT', 'REMARQUE'],
      dtype='object')

In [8]:
df.describe()

,N°,Unnamed: 1,NCG,NCG.1,SODEXO,HT,TVA,TF,TTC,RS,NET RS
count,588.000000,588.000000,588.000000,588.000000,14.000000,586.000000,451.000000,422.000000,587.000000,135.000000,417.000000
mean,295.333333,1.001701,21978.892857,607898.010204,2363.914857,404.661357,42.831963,1.469782,494.146212,87.133935,614.811510
std,170.126262,0.041239,94816.541380,54226.932333,1829.929959,942.652007,152.604166,5.995234,1125.899138,136.283086,1249.926804
min,1.000000,1.000000,401.000000,228100.000000,0.000000,-4500.000000,-855.000000,0.000000,-5354.000000,0.000000,-5354.000000
25%,148.750000,1.000000,401.000000,606500.000000,15.950000,20.000000,0.000000,0.000000,20.000000,0.000000,17.500000
50%,295.500000,1.000000,401.000000,606500.000000,3420.550000,99.818500,0.000000,0.000000,100.000000,0.000000,70.000000
75%,442.250000,1.000000,401.000000,623000.000000,3800.456000,196.924500,17.615140,1.000000,211.955000,160.000000,500.000000
max,589.000000,2.000000,437910.000000,665402.000000,4007.800000,6302.000000,1197.380000,37.652000,7500.380000,750.038000,6750.342000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588 entries, 0 to 587
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N°           588 non-null    int64
 1   Unnamed: 1   588 non-null    int64
 2   DATE         588 non-null    datetime64[ns]
 3   NCG          588 non-null    int64
 4   ICG          588 non-null    object
 5   NCT          559 non-null    object
 6   NCG.1        588 non-null    int64
 7   N° FCT       584 non-null    object
 8   DESCRIPTION  521 non-null    object
 9   SODEXO       14 non-null     float64
 10  HT           586 non-null    float64
 11  TVA          451 non-null    float64
 12  TF           422 non-null    float64
 13  TTC          587 non-null    float64
 14  RS           135 non-null    float64
 15  NET RS       417 non-null    float64
 16  PAIEMENT     582 non-null    object
 17  REMARQUE     73 non-null     object
dtypes: datetime64[ns](1), float64(7), int64(4), object(6)
memory usage: 82.8+ KB

In [10]:
df.dtypes

N°                      int64
Unnamed: 1              int64
DATE           datetime64[ns]
NCG                     int64
ICG                    object
NCT                    object
NCG.1                   int64
N° FCT                 object
DESCRIPTION            object
SODEXO                float64
HT                    float64
TVA                   float64
TF                    float64
TTC                   float64
RS                    float64
NET RS                float64
PAIEMENT               object
REMARQUE               object
dtype: object

In [12]:
df.head()

,N°,Unnamed: 1,DATE,NCG,ICG,NCT,NCG.1,N° FCT,DESCRIPTION,SODEXO,HT,TVA,TF,TTC,RS,NET RS,PAIEMENT,REMARQUE
0,1,1,2023-01-12,401,FSR AUX,401S02,228300,23-0013,IMPRIMANTE HP,NaN,4150.00,290.500,1.0,4441.500,44.415,4397.085,CHQ 0000016 (26/1/29)BIAT,IMMO / reg des factures f 22-208 + 23-0013°)
1,2,1,2023-01-05,401,FSR AUX,401S02,615002,23-0008,reparation imprimante,NaN,60.00,11.400,1.0,72.400,0.000,72.400,CHQ 0000016 (26/1/29)BIAT,annulee
2,3,1,2023-01-16,401,FSR AUX,401D02,606200,00001317,produits bureautiques,NaN,43.53,8.271,1.0,52.801,0.000,52.801,Espece,NaN
3,4,1,2023-01-26,401,FSR AUX,401D01,606100,05,spot led,NaN,239.45,45.495,1.0,285.945,0.000,285.945,Espece,NaN
4,5,1,2023-01-04,402,SOUS TRAITANTS,402S01,611002,2023BLF/00003,PROJET:- realisation d4un prog de transformati...,NaN,1100.00,209.000,1.0,1310.000,13.100,1296.900,CHQ4000410 ZITOUNA,NaN

In [13]:
df.tail()

,N°,Unnamed: 1,DATE,NCG,ICG,NCT,NCG.1,N° FCT,DESCRIPTION,SODEXO,HT,TVA,TF,TTC,RS,NET RS,PAIEMENT,REMARQUE
583,585,1,2023-12-09,401,FSR AUX,401C01,606500,AZIZ,CARBURANT,NaN,100.000,0.000,0.0,100.0,NaN,NaN,Espece,NaN
584,586,1,2023-12-26,401,FSR AUX,401D01,606100,AZIZ,produit médical,NaN,100.000,0.000,0.0,100.0,NaN,NaN,Espece,NaN
585,587,1,2023-12-31,401,FSR AUX,401S03,606401,221050170,A12 AUTO RELEVE COMPTEUR DEF,NaN,517.856,206.144,0.0,724.0,NaN,NaN,NaN,NaN
586,588,1,2023-12-31,401,FSR AUX,401S03,606403,221050370,B13 AUTO RELEVE COMPTEUR DEF,NaN,669.186,188.814,0.0,858.0,NaN,NaN,NaN,NaN
587,589,1,2023-12-31,401,FSR AUX,401S03,606402,221050350,B11 AUTO RELEVE COMPTEUR DEF,NaN,338.147,61.853,0.0,400.0,NaN,NaN,NaN,NaN